# Generated by Django 4.1.1 on 2022-10-05 19:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_remove_component_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='supported_catalog_versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NIST_800_53_rev5', 'NIST 800-53 rev5'), ('NIST_800_53_rev4', 'NIST 800-53 rev4')], max_length=16), help_text='Catalog versions that this component is defined on.', size=None),
        ),
    ]
